// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class BirdType
    {
        public BirdType()
        {
            Bird = new HashSet<Bird>();
        }

        [Key]
        [Column("BirdTypeID")]
        [StringLength(10)]
        public string BirdTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string BirdTypeName { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        public bool Status { get; set; }

        [InverseProperty("BirdTypeNavigation")]
        public virtual ICollection<Bird> Bird { get; set; }
    }
}