// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class BirdProduct
    {
        [Key]
        [Column("BirdID")]
        [StringLength(10)]
        public string BirdId { get; set; }
        [Key]
        [Column("ProductID")]
        [StringLength(10)]
        public string ProductId { get; set; }
        public bool Status { get; set; }

        [ForeignKey("BirdId")]
        [InverseProperty("BirdProduct")]
        public virtual Bird Bird { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("BirdProduct")]
        public virtual Product Product { get; set; }
    }
}