// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class Blog
    {
        public Blog()
        {
            Image = new HashSet<Image>();
        }

        [Key]
        [Column("BlogID")]
        [StringLength(10)]
        public string BlogId { get; set; }
        [Required]
        [Column("UserID")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Required]
        [StringLength(100)]
        public string BlogTitle { get; set; }
        [Required]
        [StringLength(100)]
        public string BlogSummary { get; set; }
        [Required]
        public string BlogContent { get; set; }
        [Required]
        [StringLength(50)]
        public string BlogType { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreateAt { get; set; }
        public bool Status { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Blog")]
        public virtual User User { get; set; }
        [InverseProperty("Blog")]
        public virtual ICollection<Image> Image { get; set; }
    }
}