// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class Color
    {
        public Color()
        {
            ColorProduct = new HashSet<ColorProduct>();
            ProductCustom = new HashSet<ProductCustom>();
        }

        [Key]
        [Column("ColorID")]
        [StringLength(10)]
        public string ColorId { get; set; }
        [Column("ImageURL")]
        public string ImageUrl { get; set; }
        [Required]
        [StringLength(30)]
        public string ColorName { get; set; }
        [Column("MaterialID")]
        [StringLength(10)]
        public string MaterialId { get; set; }
        public bool IsCustom { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("Color")]
        public virtual Material Material { get; set; }
        [InverseProperty("Color")]
        public virtual ICollection<ColorProduct> ColorProduct { get; set; }
        [InverseProperty("ProductColorNavigation")]
        public virtual ICollection<ProductCustom> ProductCustom { get; set; }
    }
}