// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class FeedBack
    {
        public FeedBack()
        {
            InverseReply = new HashSet<FeedBack>();
            OrderDetail = new HashSet<OrderDetail>();
        }

        [Key]
        [Column("FeedbackID")]
        [StringLength(10)]
        public string FeedbackId { get; set; }
        [Required]
        [Column("UserID")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Required]
        [Column("ReplyID")]
        [StringLength(10)]
        public string ReplyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTime { get; set; }
        public string FeedbackContent { get; set; }
        [StringLength(1)]
        public string Rating { get; set; }
        public bool Status { get; set; }

        [ForeignKey("ReplyId")]
        [InverseProperty("InverseReply")]
        public virtual FeedBack Reply { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("FeedBack")]
        public virtual User User { get; set; }
        [InverseProperty("Reply")]
        public virtual ICollection<FeedBack> InverseReply { get; set; }
        [InverseProperty("Feedback")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}