// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class Image
    {
        [Key]
        [Column("ImageID")]
        [StringLength(10)]
        public string ImageId { get; set; }
        [Column("BlogID")]
        [StringLength(10)]
        public string BlogId { get; set; }
        [Column("ProductID")]
        [StringLength(10)]
        public string ProductId { get; set; }
        [Column("StyleID")]
        [StringLength(10)]
        public string StyleId { get; set; }
        [Column("SizeID")]
        [StringLength(10)]
        public string SizeId { get; set; }
        [Column("MaterialID")]
        [StringLength(10)]
        public string MaterialId { get; set; }
        [Column("BirdID")]
        [StringLength(10)]
        public string BirdId { get; set; }
        [Required]
        [Column("ImageURL")]
        public string ImageUrl { get; set; }

        [ForeignKey("BirdId")]
        [InverseProperty("Image")]
        public virtual Bird Bird { get; set; }
        [ForeignKey("BlogId")]
        [InverseProperty("Image")]
        public virtual Blog Blog { get; set; }
        [ForeignKey("MaterialId")]
        [InverseProperty("Image")]
        public virtual Material Material { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("Image")]
        public virtual Product Product { get; set; }
        [ForeignKey("SizeId")]
        [InverseProperty("Image")]
        public virtual Size Size { get; set; }
        [ForeignKey("StyleId")]
        [InverseProperty("Image")]
        public virtual Style Style { get; set; }
    }
}