// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetail = new HashSet<OrderDetail>();
            Payment = new HashSet<Payment>();
            VoucherUserOrder = new HashSet<VoucherUserOrder>();
        }

        [Key]
        [Column("OrderID")]
        [StringLength(10)]
        public string OrderId { get; set; }
        [Required]
        [Column("UserID")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Required]
        public string Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Column("total", TypeName = "decimal(18, 0)")]
        public decimal Total { get; set; }
        public bool Status { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Order")]
        public virtual User User { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<Payment> Payment { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<VoucherUserOrder> VoucherUserOrder { get; set; }
    }
}