// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class OrderDetail
    {
        [Key]
        [Column("OrderID")]
        [StringLength(10)]
        public string OrderId { get; set; }
        [Key]
        [Column("ProductID")]
        [StringLength(10)]
        public string ProductId { get; set; }
        [Column("FeedbackID")]
        [StringLength(10)]
        public string FeedbackId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        public bool Status { get; set; }
        public bool IsCustom { get; set; }

        [ForeignKey("FeedbackId")]
        [InverseProperty("OrderDetail")]
        public virtual FeedBack Feedback { get; set; }
        [ForeignKey("OrderId")]
        [InverseProperty("OrderDetail")]
        public virtual Order Order { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("OrderDetail")]
        public virtual Product Product { get; set; }
    }
}