// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class Product
    {
        public Product()
        {
            BirdProduct = new HashSet<BirdProduct>();
            CategoryProduct = new HashSet<CategoryProduct>();
            ColorProduct = new HashSet<ColorProduct>();
            Image = new HashSet<Image>();
            MaterialProduct = new HashSet<MaterialProduct>();
            OrderDetail = new HashSet<OrderDetail>();
            SizeProduct = new HashSet<SizeProduct>();
            StyleProduct = new HashSet<StyleProduct>();
        }

        [Key]
        [Column("ProductID")]
        [StringLength(10)]
        public string ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        public int? Discount { get; set; }
        public bool Status { get; set; }

        [InverseProperty("Product")]
        public virtual ICollection<BirdProduct> BirdProduct { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<CategoryProduct> CategoryProduct { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ColorProduct> ColorProduct { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<Image> Image { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<MaterialProduct> MaterialProduct { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<SizeProduct> SizeProduct { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<StyleProduct> StyleProduct { get; set; }
    }
}