// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class SizeProduct
    {
        [Key]
        [Column("ProductID")]
        [StringLength(10)]
        public string ProductId { get; set; }
        [Key]
        [Column("SizeID")]
        [StringLength(10)]
        public string SizeId { get; set; }
        public bool Status { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("SizeProduct")]
        public virtual Product Product { get; set; }
        [ForeignKey("SizeId")]
        [InverseProperty("SizeProduct")]
        public virtual Size Size { get; set; }
    }
}