// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace backend_not_clear.Models
{
    public partial class User
    {
        public User()
        {
            Blog = new HashSet<Blog>();
            FeedBack = new HashSet<FeedBack>();
            Order = new HashSet<Order>();
            ProductCustom = new HashSet<ProductCustom>();
            VoucherUserOrder = new HashSet<VoucherUserOrder>();
        }

        [Key]
        [Column("UserID")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Required]
        [Column("RoleID")]
        [StringLength(10)]
        public string RoleId { get; set; }
        [Column("ImageURL")]
        public string ImageUrl { get; set; }
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        public string PassWord { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        public bool? Gender { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBird { get; set; }
        public string Address { get; set; }
        [StringLength(11)]
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("User")]
        public virtual Role Role { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Blog> Blog { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<FeedBack> FeedBack { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Order> Order { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ProductCustom> ProductCustom { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<VoucherUserOrder> VoucherUserOrder { get; set; }
    }
}